# Default config for the local development environment.
path: /var/www/html

core install:
  title: Block Plugin Template
  admin_user: admin
  admin_password: password
  admin_email: admin@block-plugin-template.local

